name: Tag
version: 1.4
main: io.codejava.mc.tag.TagGamePlugin
api-version: 1.21
commands:
  tagstart:
    usage: /tagstart <tagger> <runner>
    description: Starts a tag game between two players. Korean.
