name: Build Tag Plugin

on:
  push:
    paths:
      - 'plugin.yml'
      - 'src/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 24

    - name: Download dependencies
      run: |
        mkdir -p lib
        wget -O lib/paper-api.jar https://repo.papermc.io/repository/maven-snapshots/io/papermc/paper/paper-api/1.21.5-R0.1-SNAPSHOT/paper-api-1.21.5-R0.1-20250618.110345-23.jar
        wget -O lib/adventure-api.jar https://repo1.maven.org/maven2/net/kyori/adventure-api/4.13.1/adventure-api-4.13.1.jar
        wget -O lib/adventure-platform-bukkit.jar https://repo1.maven.org/maven2/net/kyori/adventure-platform-bukkit/4.3.1/adventure-platform-bukkit-4.3.1.jar
        wget -O lib/adventure-text-serializer-legacy.jar https://repo1.maven.org/maven2/net/kyori/adventure-text-serializer-legacy/4.13.1/adventure-text-serializer-legacy-4.13.1.jar

    - name: Compile plugin
      run: |
        mkdir -p out
        javac -cp "lib/*" -d out src/io/codejava/mc/tag/TagGamePlugin.java
        cp plugin.yml out/
        cd out
        jar cf TagGame.jar plugin.yml io

    - name: Upload JAR as artifact
      uses: actions/upload-artifact@v4
      with:
        name: TagGamePlugin
        path: out/TagGame.jar
